### ISSUE TITLE
pip installation does not work

### ISSUE THREAD

**Issue by ialbert** [tariqdaouda/pyGeno#2]
`pip install pyGeno`

then

```
>>> import pyGeno.bootstrap as B
>>> B.printDatawraps()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ialbert/.virtualenvs/work/lib/python2.7/site-packages/pyGeno/bootstrap.py", line 24, in printDatawraps
    l = listDatawraps()
  File "/Users/ialbert/.virtualenvs/work/lib/python2.7/site-packages/pyGeno/bootstrap.py", line 12, in listDatawraps
    for f in os.listdir(os.path.join(this_dir, "bootstrap_data/genomes")) :
OSError: [Errno 2] No such file or directory: '/Users/ialbert/.virtualenvs/work/lib/python2.7/site-packages/pyGeno/bootstrap_data/genomes'
```

**Comment by tariqdaouda** [comment]
Hi,

The problem was that the folders containing the datawraps were not included in the pip version. I'm sorry  it is fixed now. Only the bootstrap module suffered from it, the rest of the installation went fine and you should be able to use it just fine. I would recommend nonetheless upgrading your version by doing:

pip install --upgrade pyGeno

or switching to the git version, to get the bleeding edge updates.

Cheers,
