### ISSUE TITLE
Cannot install pyGeno successfully

### ISSUE THREAD

**Issue by lotus-devo** [tariqdaouda/pyGeno#65]
I tried to install pyGeno in python2.7 ubuntu16.04.10，but Can't install successfully. The error message is as follows：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dongl/.local/lib/python2.7/site-packages/pyGeno/__init__.py", line 3, in <module>
    from .configuration import pyGeno_init
  File "/home/dongl/.local/lib/python2.7/site-packages/pyGeno/configuration.py", line 3, in <module>
    import rabaDB.rabaSetup
  File "/home/dongl/.local/lib/python2.7/site-packages/rabaDB/rabaSetup.py", line 24
    class RabaConfiguration(object, metaclass=RabaNameSpaceSingleton) :
                                             ^
SyntaxError: invalid syntax

how can I solve this problem? Please help me

**Comment by lucventurini** [comment]
Dear @lotus-devo ,

Most probably the issue is that you are using Python 2.7. Should you switch to Python3, the code should become syntactically valid and therefore PyGeno should function correctly.

Kind regards
