### ISSUE TITLE
Installation not working on Mac OS Yosemite 10.10.5

### ISSUE THREAD

**Issue by genomeo** [tariqdaouda/pyGeno#7]
Hi Tariq,

Following the recommended installation, I tried to run this simple script:

```python
#! /usr/local/bin/python
from pyGeno.Genome import *
g = Genome(name = "GRCh37.75")
sys.exit()
```
But I get this error:

```text
Traceback (most recent call last):
  File "./script.py", line 8, in <module>
    g = Genome(name = "GRCh37.75")
  File "/usr/local/pyGeno/pyGeno/Genome.py", line 67, in __init__
    pyGenoRabaObjectWrapper.__init__(self, *args, **kwargs)
  File "/usr/local/pyGeno/pyGeno/pyGenoObjectBases.py", line 83, in __init__
    self.wrapped_object = self._wrapped_class(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rabaDB/Raba.py", line 301, in __call__
    raise KeyError("Couldn't find any object that fit the arguments you've prodided to the constructor")
KeyError: "Couldn't find any object that fit the arguments you've prodided to the constructor"
```
Any ideas?

G.

**Comment by tariqdaouda** [comment]
Hi!

Thank you for filling this one.
No panic, several people in the lab are running pyGeno on Macs, so I know it usually runs smoothly.

This is the error that you should get if pyGeno cannot find the specified genome.
Have you imported the GRCh37.75?

You can do it with:

``` python
import pyGeno.bootstrap as B
B.importGenome("Human.GRCh37.75.tar.gz")
```
You can list of all the available datawraps for bootstrapping using:

``` python
import pyGeno.bootstrap as B
B.printDatawraps()
```
